import os
import sys

def combine_python_files(target_dir, output_file):
    """
    Combine all .py files in the target directory into a single Python file.

    Args:
        target_dir (str): Path to the directory containing .py files to combine.
        output_file (str): Path to the output Python file.
    """
    if not os.path.isdir(target_dir):
        print(f"Error: The target directory '{target_dir}' does not exist or is not a directory.")
        return

    # Ensure the output file is not inside the target directory to prevent recursion
    abs_output_path = os.path.abspath(output_file)
    abs_target_dir = os.path.abspath(target_dir)
    if os.path.commonpath([abs_output_path]) == os.path.commonpath([abs_output_path, abs_target_dir]):
        print("Error: The output file must not be inside the target directory.")
        return

    # Get a sorted list of .py files in the target directory
    py_files = sorted([
        f for f in os.listdir(target_dir)
        if f.endswith('.py') and os.path.isfile(os.path.join(target_dir, f))
    ])

    if not py_files:
        print(f"No Python files found in the directory '{target_dir}'.")
        return

    try:
        with open(output_file, 'w', encoding='utf-8') as outfile:
            outfile.write("# Combined Python File\n")
            outfile.write("# This file is autogenerated by combine_python_files.py\n\n")

            for filename in py_files:
                file_path = os.path.join(target_dir, filename)
                outfile.write(f"# ----- Begin {filename} -----\n")
                with open(file_path, 'r', encoding='utf-8') as infile:
                    contents = infile.read()
                    outfile.write(contents)
                outfile.write(f"\n# ----- End {filename} -----\n\n")

        print(f"Successfully combined {len(py_files)} files into '{output_file}'.")
    except Exception as e:
        print(f"An error occurred while combining files: {e}")

def print_usage():
    """
    Print usage instructions.
    """
    script_name = os.path.basename(sys.argv[0])
    print(f"Usage: python {script_name} <target_directory> <output_file>")
    print("Example:")
    print(f"    python {script_name} ./my_python_files combined.py")

if __name__ == '__main__':
    if len(sys.argv) != 3:
        print("Error: Incorrect number of arguments.")
        print_usage()
        sys.exit(1)

    target_directory = sys.argv[1]
    output_python_file = sys.argv[2]

    combine_python_files(target_directory, output_python_file)
